#!/bin/bash

# Set up a Decred node.
#
# To use run:
# curl -L https://node.dcr.pw/alpine | ash
#
# Check it's running with:
# openrc status dcrd

# Update
apk update && apk upgrade
apk add curl

# Set Decred version, CPU architecture, binaries archive name.
v=v1.7.2
a=amd64
b=decred-linux-${a}-${v}.tar.gz

# Download Decred binaries archive.
curl -L -O https://github.com/decred/decred-binaries/releases/download/${v}/${b}

# Extract Decred binaries.
tar -xf ${b} --strip-components 1 -C /usr/local/bin/

# Create dcrd service.
cat > /etc/init.d/dcrd <<EOF
#!/sbin/openrc-run

name="dcrd"
command="dcrd"
command_background=true
pidfile="/run/${RC_SVCNAME}.pid"
EOF

chmod +x /etc/init.d/dcrd

# Enable + (re)start service.
rc-update add dcrd
rc-service dcrd restart
